package q1;

import java.util.Date;

public final class StockReport extends Entity {
    private Date reportDate;
    private String remarks;
    
    public StockReport(int id, Date createdDate, Date updatedDate, 
                      Date reportDate, String remarks) {
        super(id, createdDate, updatedDate);
        setReportDate(reportDate);
        setRemarks(remarks);
    }
    
    // Getters and Setters
    public Date getReportDate() { return reportDate; }
    public String getRemarks() { return remarks; }
    
    public void setReportDate(Date reportDate) {
        if (reportDate == null) throw new IllegalArgumentException("Report date cannot be null");
        this.reportDate = reportDate;
    }
    
    public void setRemarks(String remarks) {
        if (remarks == null) remarks = "";
        this.remarks = remarks;
    }
    
    public void generateReport() {
        StringBuilder report = new StringBuilder();
        report.append("=== STOCK MANAGEMENT SYSTEM REPORT ===\n");
        report.append("Report Date: ").append(reportDate).append("\n");
        report.append("Remarks: ").append(remarks).append("\n");
        report.append("Generated By Student ID: 27120\n");
        report.append("Summary of total stock and sales:\n");
        report.append("- Total Items in Inventory: [Calculated Value]\n");
        report.append("- Total Stock Value: [Calculated Value]\n");
        report.append("- Total Sales: [Calculated Value]\n");
        report.append("- Total Purchases: [Calculated Value]\n");
        report.append("=== END OF REPORT ===\n");
        
      
        String finalOutput = "27120_" + report.toString();
        System.out.println(finalOutput);
    }
}